### ISSUE TITLE
fork 이후 원본 저장소와 연결을 위해 다음 문서를 숙지해주세요

### ISSUE THREAD

**Issue by yevgnenll** [manducku/TDD_Study#2]
fork 된 프로젝트는 원본 remote인 
[manducu/TDD_study](https://github.com/manducku/TDD_Study) 와 분리됩니다.

fork된 내 working directory에서 원본 파일 내용을 올바르게 sync 하기 위해서

아래의 문서를 읽고 숙지해주세요~

민수 성필이 저 3명은 필수라능ㅋ

1. https://help.github.com/articles/configuring-a-remote-for-a-fork/ 
   - 내 git에 upstream remote 설정하기
2. https://help.github.com/articles/syncing-a-fork/
   - 연결된 upstream과 sync하기

**Comment by goohooh** [comment]
👍 👍 👍 👍 👍
